### PR TITLE
turned off RX_LED and TX_LED, thanks for the port to arduboy2 lib

### PR DESCRIPTION
**Pull request by joe-speedboat**
Hi, thanks for the port.
I just disabled the rx and tx led, so it is nicer to play in the dark :-)

### CODE REVIEW

**Comment by MLXXXp** [comment]
This game doesn't control any LEDs. Are you using a real Arduboy?

**Comment by joe-speedboat** [comment]
Yes, I use real one, from kickstarter project. v1.0
Yellow and Orange LED next USB where always on, so I set them to OFF.
If you do not set, it is undefined.

**Comment by MLXXXp** [comment]
They don't come on with my Kickstarter Arduboy and nobody else has complained about this.

> If you do not set, it is undefined.

No, they are initialised by the bootloader and/or the Arduino USB code.

Have you selected board type _Arduboy_ or _Arduino Leonardo_ when you upload the sketch from the IDE?

**Comment by joe-speedboat** [comment]
That's probably the point, I used "Arduino Micro". 
Which board url do you use to get Arduboy board?
I have the "1 of 10 000" edition board from kickstarter (first batch, but not the DEV board).

**Comment by MLXXXp** [comment]
> Which board url do you use to get Arduboy board?

It's given in Step 2 of the [Arduboy Quick Start Guide](https://community.arduboy.com/t/quick-start-guide/2790).

https://arduboy.github.io/board-support/package_arduboy_index.json

**Comment by joe-speedboat** [comment]
Oh sorry. Ill check that. 
So just skip it ...
Thanks for the great work! Happy new Year!

**Pull request closed without merging**
